/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSuppliersRouteImport } from './routes/dashboard.suppliers'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMovementsRouteImport } from './routes/dashboard.movements'
import { Route as DashboardMedicinesRouteImport } from './routes/dashboard.medicines'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardImportExportRouteImport } from './routes/dashboard.import-export'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuppliersRoute = DashboardSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMovementsRoute = DashboardMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicinesRoute = DashboardMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportExportRoute = DashboardImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/import-export': typeof DashboardImportExportRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/medicines': typeof DashboardMedicinesRoute
  '/dashboard/movements': typeof DashboardMovementsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppliers': typeof DashboardSuppliersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/import-export': typeof DashboardImportExportRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/medicines': typeof DashboardMedicinesRoute
  '/dashboard/movements': typeof DashboardMovementsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppliers': typeof DashboardSuppliersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/import-export': typeof DashboardImportExportRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/medicines': typeof DashboardMedicinesRoute
  '/dashboard/movements': typeof DashboardMovementsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppliers': typeof DashboardSuppliersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/audit'
    | '/dashboard/import-export'
    | '/dashboard/inventory'
    | '/dashboard/medicines'
    | '/dashboard/movements'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/audit'
    | '/dashboard/import-export'
    | '/dashboard/inventory'
    | '/dashboard/medicines'
    | '/dashboard/movements'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/alerts'
    | '/dashboard/audit'
    | '/dashboard/import-export'
    | '/dashboard/inventory'
    | '/dashboard/medicines'
    | '/dashboard/movements'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suppliers': {
      id: '/dashboard/suppliers'
      path: '/suppliers'
      fullPath: '/dashboard/suppliers'
      preLoaderRoute: typeof DashboardSuppliersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/movements': {
      id: '/dashboard/movements'
      path: '/movements'
      fullPath: '/dashboard/movements'
      preLoaderRoute: typeof DashboardMovementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/medicines': {
      id: '/dashboard/medicines'
      path: '/medicines'
      fullPath: '/dashboard/medicines'
      preLoaderRoute: typeof DashboardMedicinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import-export': {
      id: '/dashboard/import-export'
      path: '/import-export'
      fullPath: '/dashboard/import-export'
      preLoaderRoute: typeof DashboardImportExportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardImportExportRoute: typeof DashboardImportExportRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardMedicinesRoute: typeof DashboardMedicinesRoute
  DashboardMovementsRoute: typeof DashboardMovementsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuppliersRoute: typeof DashboardSuppliersRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardImportExportRoute: DashboardImportExportRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardMedicinesRoute: DashboardMedicinesRoute,
  DashboardMovementsRoute: DashboardMovementsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuppliersRoute: DashboardSuppliersRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
